# Generated by Django 3.2.9 on 2021-12-06 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userreport_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='camps',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='wing',
        ),
    ]
